### ISSUE TITLE
BVE freezes when 32bit DLL is used via DetailManager

### ISSUE THREAD

**Issue by bvews** [bvews/ats-plugin-rust#1]
BVE Trainsim freezes when the 32bit DLL compiled from this project is loaded and called its functions from 32bit BVE (Version 5.8) via 32bit DetailManager.dll. This behavior suggests memory access violation may be occered at calling functions of the DLL.

The probrem is not occered when the 32bit DLL is loaded from the 32bit BVE directly, or the 64bit DLL is loaded from 64bit BVE (Version 6) directly or via 64bit DetailManager.

**Comment by magicant** [comment]
I suppose this commit should fix the issue: https://github.com/magicant/ats_plugin_rust/commit/9fc8c16005c6afdd7e2ee77ce308d34412fa10bc

**Comment by bvews** [comment]
It works fine! Thank you very much your improvement!
